name: CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.operating-system }}
        env:
            SYMFONY_ENV: behat
            DB_HOST: localhost
            DB_TYPE: mysql
            DB_ROOT_PASSWORD: root
            DB_EZ_USER: ezp
            DB_EZ_PASSWORD: ezp
            DB_EZ_DATABASE: behattestdb
            PHP_VERSION: ${{ matrix.php }}
            EZ_COMPOSER_LOCK: ${{ matrix.ez_composer_lock }}
            EZ_BUNDLES: ${{ matrix.ez_bundles }}
            EZ_PACKAGES: ${{ matrix.ez_packages }}
            EZ_LEGACY_EXTENSIONS: ezworkflowenginebridge
        strategy:
            fail-fast: false
            matrix:
                # @see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners for available os versions
                # @todo add some tests running on 'windows-latest'
                include:
                    - php: '5.6'
                      ez_bundles: 'Kaliop\eZWorkflowEngineBundle\EzWorkflowEngineBundle Kaliop\eZMigrationBundle\EzMigrationBundle'
                      # in this case ez_packages is ignored for dependencies installation, but it is used by teststack
                      # scripts as indicator of the ezp version in use
                      ez_packages: 'ezsystems/ezpublish-community:~2014.11.1'
                      ez_composer_lock: Tests/composer/composer-cp_2104.11.1.lock
                      operating-system: 'ubuntu-20.04'
                    - php: '7.0'
                      ez_bundles: 'Kaliop\eZWorkflowEngineBundle\EzWorkflowEngineBundle Kaliop\eZMigrationBundle\EzMigrationBundle'
                      ez_packages: 'ezsystems/ezplatform:~1.7.9 kaliop/ezmigrationbundle:~5.14.0 ezsystems/behatbundle:^6.3'
                      ez_composer_lock: ''
                      operating-system: 'ubuntu-20.04'
                    - php: '7.1'
                      ez_bundles: 'Kaliop\eZWorkflowEngineBundle\EzWorkflowEngineBundle Kaliop\eZMigrationBundle\EzMigrationBundle'
                      ez_packages: 'ezsystems/ezplatform:~1.13.5 kaliop/ezmigrationbundle:~5.15.0 ezsystems/behatbundle:^6.3'
                      ez_composer_lock: ''
                      operating-system: 'ubuntu-20.04'
                    - php: '7.2'
                      ez_bundles: 'Kaliop\eZWorkflowEngineBundle\EzWorkflowEngineBundle Kaliop\eZMigrationBundle\EzMigrationBundle'
                      ez_packages: 'ezsystems/ezplatform:~2.3.2 kaliop/ezmigrationbundle:~6.0.0 ezsystems/behatbundle:^6.5 sensio/generator-bundle'
                      ez_composer_lock: ''
                      operating-system: 'ubuntu-22.04'
                    - php: '7.3'
                      ez_bundles: 'Kaliop\eZWorkflowEngineBundle\EzWorkflowEngineBundle Kaliop\eZMigrationBundle\EzMigrationBundle'
                      ez_packages: 'ezsystems/ezplatform:~2.4.2 kaliop/ezmigrationbundle:~6.1.0 ezsystems/behatbundle:^6.5 sensio/generator-bundle'
                      ez_composer_lock: ''
                      operating-system: 'ubuntu-22.04'
                    - php: '7.4'
                      ez_bundles: 'Kaliop\eZWorkflowEngineBundle\EzWorkflowEngineBundle Kaliop\eZMigrationBundle\EzMigrationBundle'
                      ez_packages: 'ezsystems/ezplatform:^2.5.15 kaliop/ezmigrationbundle:^6.1 ezsystems/behatbundle:^7.0 sensio/generator-bundle overblog/graphiql-bundle'
                      ez_composer_lock: ''
                      operating-system: 'ubuntu-22.04'
#                    - php: "8.0"
#                      ez_bundles: ''
#                      ez_packages: ''
#                      ez_composer_lock: ''
#                      operating-system: 'ubuntu-20.04'
#                    - php: "8.1"
#                      ez_bundles: ''
#                      ez_packages: ''
#                      ez_composer_lock: ''
#                      operating-system: 'ubuntu-20.04'
        steps:
            -
                uses: actions/checkout@v2
            # Although this action is useful, we prefer to use the same script to set up php that we use for the
            # docker image used for local testing. This allows us to make sure that script is always in good shape
            #-
            #    uses: shivammathur/setup-php@v2
            #    with:
            #        php-version: ${{ matrix.php }}
            #        extensions: curl, dom, mbstring, xsl
            #        ini-values: 'cgi.fix_pathinfo=1, always_populate_raw_post_data=-1'
            #        #tools: phpunit/phpunit:a_version_compatible_with_php_5.3-5.5
            #        # NB: this disables xdebug completely
            #        coverage: none
            -
                run: |
                    # @todo we should check out a specific tag/branch for stability, or at last the latest tag...
                    git clone --depth 1 https://github.com/tanoconsulting/euts.git teststack
                    # just in case...
                    chmod 755 ./teststack/bin/*.sh  ./teststack/bin/setup/*.sh
            # Avoid downloading composer deps on every workflow. Is this useful/working for us?
            #-
            #    uses: actions/cache@v2
            #    with:
            #        path: /tmp/composer-cache
            #        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            # This sets up php and configures plus starts mysql
            -
                run: './teststack/bin/setup.sh'
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            -
                if: ${{ matrix.php == '7.4' }}
                run: |
                    ./teststack/bin/runtests.sh -c coverage.clover
                    #if [ -f coverage.clover ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
                    if [ -f coverage.clover ]; then curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -t ${CODECOV_TOKEN} -f coverage.clover; fi
            -
                if: ${{ matrix.php != '7.4' }}
                run: './teststack/bin/runtests.sh'
            -
                if: ${{ failure() }}
                run: |
                    #env
                    #php -i
                    #ps auxwww
                    #dpkg --list | grep php
                    #pwd
                    #sudo env
                    #ls -ltr /var/log
                    sudo cat /var/log/php*.log
